config/routes.rb
Ploy::Application.routes.draw do
  resources :candidates
  root :to => "candidates#index"
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  def index
    @candidates = Candidate.all
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(params[:candidate])
    if @candidate.save
      redirect_to @candidate, :notice => "Successfully created candidate."
    else
      render :action => 'new'
    end
  end

  def edit
    @candidate = Candidate.find(params[:id])
  end

  def update
    @candidate = Candidate.find(params[:id])
    if @candidate.update_attributes(params[:candidate])
      redirect_to @candidate, :notice  => "Successfully updated candidate."
    else
      render :action => 'edit'
    end
  end

  def show
    @candidate = Candidate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(title)
   "#{title} | Potential Employee Application"
  end

  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

end

app/views/candidates/_form.html.erb
<%= form_for @candidate do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :github_name %><br />
    <%= f.text_field :github_name %>
  </p>
   <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :linked_in %><br />
    <%= f.text_field :linked_in %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/candidates/edit.html.erb
<% title "Edit Candidate" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @candidate %> |
  <%= link_to "View All", candidates_path %>
</p>

app/views/candidates/index.html.erb
<% title "Candidates" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for candidate in @candidates %>
    <tr>
      <td><%= candidate.name %></td>
      <td><%= link_to "Show", candidate %></td>
      <td><%= link_to "Edit", edit_candidate_path(candidate) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Candidate", new_candidate_path %></p>

app/views/candidates/new.html.erb
<% title "New Candidate" %>

<%= render 'form' %>

<p><%= link_to "Back to List", candidates_path %></p>

app/views/candidates/show.html.erb
<% title "Candidate" %>

<p>
  <strong>
    <%= @candidate.name %>
  </strong>
</p>

<%= image_tag avatar_url(@candidate) %>

<p>
  <strong>Links</strong>
<ul>
  <li>
    <%= link_to "Github", "http://www.github.com/" + @candidate.github_name %>
  </li>
  <li>
    <%= link_to "LinkedIn" + @candidate.linked_in %>
  </li>
</ul>
</p>

<p>
  <strong>Email</strong>
  <%= @candidate.email %>
</p>

<p>
  <strong>Notes</strong>
  <%= @candidate.notes %>
</p>

<p>
  <%= link_to "Edit", edit_candidate_path(@candidate) %> |
  <%= link_to "View All", candidates_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ploy</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

<a href="https://github.com/bhardin/ploy"><img style="position: absolute; top: 0; right: 0; border: 0;" src="http://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub" /></a>

</body>
</html>